# Generated by Django 4.0.4 on 2022-05-30 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_director_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='age',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
    ]
