# Generated by Django 4.0.4 on 2022-05-30 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_director_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='age',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='actor',
            name='count_movie',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
