# Generated by Django 4.0.4 on 2022-05-30 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_actor_age_actor_count_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='count_movie',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
