# Generated by Django 4.0.4 on 2022-05-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_actor_count_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
