# Generated by Django 4.0.4 on 2022-05-31 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_dressingroom_actor_dressing'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='dressing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie_app.dressingroom'),
        ),
    ]
